version: "3.8"

services:
  eureka-service:
    build: ./eureka-service
    ports:
      - 8761:8761


  gateway:
    build: ./gateway
    restart: on-failure
    ports:
      - 9999:9999
    depends_on:
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka
  

  billing-service:
      build: ./billing-service
      restart: on-failure
      ports:
        - 8083:8083
      depends_on:
        - eureka-service
      environment:
        - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka


  customer-service:
      build: ./customer-service
      restart: on-failure
      ports:
        - 8082:8082
      depends_on:
        - eureka-service
      environment:
        - eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka

